export const world_arr = new Array(
	{
	    label: '亚洲',
	    options: [
		    {value: '中国'},
		    {value: '中国台湾'},
		    {value: '中国香港'},
		    {value: '中国澳门'},
		    {value: '韩国'},
		    {value: '菲律宾'},
		    {value: '日本'},
		    {value: '文莱'},
		    {value: '越南'},
		    {value: '马来西亚'},
		    {value: '印度尼西亚'},
		    {value: '新加坡'},
		    {value: '柬埔寨'},
		    {value: '泰国'},
		    {value: '缅甸'},
		    {value: '斯里兰卡'},
		    {value: '印度'},
		    {value: '尼泊尔'},
		    {value: '巴基斯坦'},
		    {value: '马尔代夫'},
		    {value: '约旦'},
		    {value: '阿联酋'},
		    {value: '朝鲜'},
		    {value: '老挝'},
		    {value: '以色列'},
		    {value: '沙特阿拉伯'},
		    {value: '哈萨克斯坦'},
		    {value: '蒙古'},
		    {value: '孟加拉'},
		    {value: '塔吉克斯坦'},
		    {value: '乌兹别克斯坦'},
		    {value: '伊朗'},
		    {value: '阿富汗'},
		    {value: '不丹'},
		    {value: '科威特'},
		    {value: '阿曼苏丹国'},
		    {value: '巴林'},
		    {value: '卡塔尔'},
		    {value: '东帝汶'},
		    {value: '叙利亚'},
		    {value: '黎巴嫩'},
		    {value: '阿塞拜疆'},
		    {value: '也门'},
		    {value: '土库曼斯坦'},
		    {value: '伊拉克'},
		    {value: '格鲁吉亚'},
		    {value: '吉尔吉斯共和国'},
		    {value: '亚美尼亚共和国'},
		    {value: '土耳其'},
	    ]
	},
	{
	    label: '欧洲',
	    options: [
	    	{value: '英国'},
	    	{value: '法国'},
	    	{value: '西班牙'},
	    	{value: '葡萄牙'},
	    	{value: '爱尔兰'},
	    	{value: '冰岛'},
	    	{value: '卢森堡'},
	    	{value: '荷兰'},
	    	{value: '比利时'},
	    	{value: '瑞士'},
	    	{value: '列支敦士登'},
	    	{value: '德国'},
	    	{value: '挪威'},
	    	{value: '瑞典'},
	    	{value: '芬兰'},
	    	{value: '爱沙尼亚'},
	    	{value: '立陶宛'},
	    	{value: '拉托维亚'},
	    	{value: '波兰'},
	    	{value: '捷克'},
	    	{value: '斯洛伐克'},
	    	{value: '奥地利'},
	    	{value: '匈牙利'},
	    	{value: '克罗地亚'},
	    	{value: '斯洛文尼亚'},
	    	{value: '意大利'},
	    	{value: '马其他'},
	    	{value: '罗马尼亚'},
	    	{value: '希腊'},
	    	{value: '俄罗斯'},
	    	{value: '塞浦路斯'},
	    	{value: '丹麦'},
	    	{value: '马耳他'},
	    	{value: '安道尔'},
	    	{value: '阿尔巴尼亚'},
	    	{value: '保加利亚'},
	    	{value: '摩纳哥'},
	    	{value: '摩尔多瓦'},
	    	{value: '马其顿'},
	    	{value: '塞尔维亚'},
	    	{value: '乌克兰'},
	    	{value: '圣马力诺'},
	    	{value: '白俄罗斯'},
	    	{value: '梵蒂冈'},
	    	{value: '黑山共和国'},
	    	{value: '波黑共和国'},
	    	{value: '苏格兰王国'},
	    ]
	},
	{
		label: '大洋洲',
		options:[
			 {value: '澳大利亚'},
			 {value: '瓦努阿图'},
			 {value: '斐济'},
			 {value: '新西兰'},
			 {value: '帕劳'},
			 {value: '所罗门群岛'},
			 {value: '密克罗尼西亚'},
			 {value: '马绍尔群岛'},
			 {value: '瑙鲁'},
			 {value: '基里巴斯'},
			 {value: '图瓦卢'},
			 {value: '萨摩亚'},
			 {value: '汤加'},
			 {value: '关岛'},
			 {value: '新喀里多尼亚'},
			 {value: '皮特凯恩群岛'},
			 {value: '纽埃'},
			 {value: '托克劳'},
			 {value: '北马里亚纳'},
			 {value: '瓦利斯和富图纳群岛'},
			 {value: '法属波利尼西亚'},
			 {value: '美属萨摩亚'},
			 {value: '巴布亚新几内亚'},
		]
	},
	{
		label:'北美洲',
		options:[
			{value:'美国'},
			{value:'加拿大'},
			{value:'墨西哥'},
			{value:'古巴'},
			{value:'哥斯达黎加'},
			{value:'牙买加'},
			{value:'多米尼克'},
			{value:'巴拿马'},
			{value:'格陵兰'},
			{value:'危地马拉'},
			{value:'伯利兹'},
			{value:'萨尔瓦多'},
			{value:'尼加拉瓜'},
			{value:'巴哈马'},
			{value:'海地'},
			{value:'多米尼加'},
			{value:'安提瓜和巴布达'},
			{value:'圣卢西亚'},
			{value:'格林纳达'},
			{value:'巴巴多斯'},
			{value:'波多黎各'},
			{value:'安圭拉'},
			{value:'瓜德罗普'},
			{value:'阿鲁巴'},
			{value:'米尼克'},
			{value:'圣基茨和尼维斯'},
			{value:'特立尼达和多巴哥'},
			{value:'英属维尔京群岛'},
			{value:'美属维尔京群岛'},
			{value:'蒙特塞拉特岛'},
			{value:'荷属安的列斯'},
			{value:'特克斯和凯科斯群岛'},
			{value:'百慕大'},
			{value:'洪都拉斯'},
			{value:'圣文森特和格林纳丁斯'},
			{value:'开曼群岛'},
		]
	},
	{
		label:'南美洲',
		options:[
			{value:'秘鲁'},
			{value:'巴西'},
			{value:'智利'},
			{value:'阿根廷'},
			{value:'苏里南共和国'},
			{value:'玻利维亚'},
			{value:'哥伦比亚'},
			{value:'委内瑞拉'},
			{value:'乌拉圭'},
			{value:'巴拉圭共和国'},
			{value:'厄瓜多尔'},
			{value:'圭亚那'}
		]
	},
	{
		label:'非洲',
		options:[
			{value:'摩洛哥'},
			{value:'突尼斯'},
			{value:'埃及'},
			{value:'埃塞俄比亚'},
			{value:'肯尼亚'},
			{value:'塞舌尔'},
			{value:'坦桑尼亚'},
			{value:'赞比亚'},
			{value:'津巴布韦'},
			{value:'毛里求斯'},
			{value:'南非'},
			{value:'尼日利亚'},
			{value:'乍得'},
			{value:'塞拉利昂'},
			{value:'贝宁'},
			{value:'多哥'},
			{value:'几内亚'},
			{value:'毛里塔尼亚'},
			{value:'马达加斯加'},
			{value:'乌干达'},
			{value:'中非'},
			{value:'几内亚比绍'},
			{value:'赤道几内亚'},
			{value:'苏丹'},
			{value:'喀麦隆'},
			{value:'科摩罗'},
			{value:'圣多美和普林西比'},
			{value:'吉布提'},
			{value:'纳米比亚'},
			{value:'塞内加尔'},
			{value:'布基纳法索'},
			{value:'尼日尔'},
			{value:'加蓬'},
			{value:'冈比亚'},
			{value:'马里'},
			{value:'佛得角'},
			{value:'阿尔及利亚'},
			{value:'加纳'},
			{value:'留尼汪'},
			{value:'利比亚'},
			{value:'卢旺达'},
			{value:'索马里'},
			{value:'布隆迪'},
			{value:'安哥拉'},
			{value:'莫桑比克'},
			{value:'博茨瓦纳'},
			{value:'利比里亚'},
			{value:'刚果民主共和国'},
			{value:'科特迪瓦'},
			{value:'厄立特里亚'},
			{value:'莱索托'},
			{value:'马拉维'},
			{value:'阿拉伯撒哈拉'},
			{value:'刚果共和国'},
			{value:'斯威士兰'},
			{value:'南苏丹'},
		]
	}
);