export const currency_data={
  '热门':[
    {value: '人民币'},
    {value: '美元'},
    {value: '欧元'},
    {value: '韩元'},
    {value: '澳元'},
    {value: '日元'},
    {value: '英镑'},
    {value: '港元'},
    {value: '加元'}
  ],
  'ABDE':[
    { value: '阿联酋迪拉姆'},
    { value: '澳元'},
    { value: '澳门元P'},
    { value: '阿尔及利亚第纳尔'},
    { value: '阿曼里亚尔'},
    { value: '埃及镑'},
    { value: '白俄罗斯卢布'},
    { value: '巴西雷亚尔'},
    { value: '波兰兹罗提'},
    { value: '巴林第纳尔'},
    { value: '保加利亚列弗'},
    { value: '冰岛克朗'},
    { value: '丹麦克朗'},
    { value: '俄罗斯卢布'}
  ],
  'FGHJ':[
    { value: '菲律宾比索'},
    { value: '港元'},
    { value: '哥伦比亚比索'},
    { value: '哥斯达黎加科朗'},
    { value: '韩元'},
    { value: '加元'},
    { value: '捷克克朗'},
    { value: '柬埔寨瑞尔'},
        
  ],
  'KLMN':[
    { value: '克罗地亚库纳'},
    { value: '卡塔尔里亚尔'},
    { value: '科威特第纳尔'},
    { value: '肯尼亚先令'},
    { value: '老挝基普'},
    { value: '罗马尼亚列伊'},
    { value: '黎巴嫩镑'},
    { value: '离岸人民币'},
    { value: '美元'},
    { value: '缅甸元'},
    { value: '马来西亚林吉特'},
    { value: '摩洛哥道拉姆'},
    { value: '墨西哥元'},
    { value: '挪威克朗'},
    { value: '南非兰特'}
  ],
  'ORST':[
    { value: '欧元'},
    { value: '人民币'},
    { value: '瑞士法郎'},
    { value: '日元'},
    { value: '瑞典克朗'},
    { value: '沙特里亚尔'},
    { value: '斯里兰卡卢比'},
    { value: '塞尔维亚第纳尔'},
    { value: '泰铢'},
    { value: '坦桑尼亚先令'}
  ],
  'WXYZ':[
    { value: '文莱元'},
    { value: '乌干达先令'},
    { value: '新的赞比亚克瓦查'},
    { value: '叙利亚镑'},
    { value: '新西兰元'},
    { value: '新土耳其里拉'},
    { value: '新加坡元'},
    { value: '新台币'},
    { value: '匈牙利福林'},
    { value: '英镑'},
    { value: '约旦第纳尔'},
    { value: '伊拉克第纳尔'},
    { value: '越南盾'},
    { value: '以色列新锡克尔'},
    { value: '印度卢比'},
    { value: '印尼卢比'},
    { value: '智利比索'}
  ],
}